import React from 'react';
import { Bot } from 'lucide-react';
import { formatDate } from '@/lib/utils';
import { Tooltip } from '@/components/ui/Tooltip';

interface AILabelProps {
  timestamp?: string;
  fieldName?: string;
  className?: string;
}

export const AILabel: React.FC<AILabelProps> = ({ timestamp, fieldName, className }) => {
  const tooltipContent = (
    <span>
      {fieldName ? `"${fieldName}" was` : 'This field was'} generated by AI
      {timestamp ? ` on ${formatDate(timestamp)}` : ''}.
      May require human review.
    </span>
  );

  return (
    <Tooltip content={tooltipContent}>
      <span
        className={`inline-flex items-center gap-1 rounded bg-amber-50 px-1.5 py-0.5 text-[10px] font-medium text-amber-700 border border-amber-200 ${className ?? ''}`}
      >
        <Bot className="h-3 w-3" />
        AI-generated
      </span>
    </Tooltip>
  );
};
